spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/eternalflame
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  profiles:
    include: API-KEY

file:
  dir: C:/Users/김성지/Pictures/springtest/